# 在 ./scripts/feeds update -a 前插入的额外 feeds。
# 格式：src-git [--force] 名称 Git地址[;分支]

src-git --force passwall_packages https://github.com/Openwrt-Passwall/openwrt-passwall-packages.git;main
src-git --force passwall_luci https://github.com/Openwrt-Passwall/openwrt-passwall.git;main
src-git --force helloworld https://github.com/fw876/helloworld.git
src-git --force sbwml_helloworld https://github.com/sbwml/openwrt_helloworld.git;v5
